BPM/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('bpmsearchapp.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls'))

]

bpmsearchapp/urls.py
from django.urls import path
from . import views

app_name = 'bpm'
urlpatterns = [
    path('', views.index, name='index'),
    path('playlist/<int:pk>', views.playlist, name='playlist'),
    path('spotifyauth/',
         views.spotify_auth, name='spotify-auth')]

bpmsearchapp/models.py
from django.db import models
import os
import base64
import json
import requests
import datetime
import pprint
import numpy as np
from datetime import timedelta

from .modules.spotify import get_access_token, pretty_time_delta, track_detail_query, recommendations_query


class Track(models.Model):
    spotify_id = models.CharField(max_length=50)
    title = models.CharField(max_length=1000)
    artist = models.CharField(max_length=50)
    duration_ms = models.IntegerField()
    duration = models.CharField(max_length=50)
    tempo = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    def create_track(song_title):
        track = track_detail_query(song_title)
        return Track(
            spotify_id=track['spotify_id'],
            title=track['title'],
            artist=track['artist'],
            duration=track['duration'],
            duration_ms=track['duration_ms'],
            tempo=int(track['tempo'])
        )


class Playlist(models.Model):
    name = models.CharField(max_length=100)
    duration = models.DurationField()
    based_on = models.ForeignKey(
        Track, on_delete=models.CASCADE)
    tracks = models.ManyToManyField(Track, related_name='tracks')
    recommended_id_string = models.CharField(max_length=5000)

    def __str__(self):
        return self.name

    def create_playlist(track, tempo, duration):
        recommendations, recommendation_ids = recommendations_query(
            track.spotify_id, tempo)
        duration_playlist = [track]
        playlist_ids = [track.spotify_id]
        target_duration = datetime.timedelta(minutes=duration+3)
        duration = datetime.timedelta(minutes=0)
        for i in enumerate(recommendations):
            if duration < target_duration:
                recommended_track = Track(
                    spotify_id=i[1].spotify_id,
                    title=i[1].title,
                    artist=i[1].artist,
                    duration=i[1].duration,
                    duration_ms=i[1].duration_ms,
                    tempo=int(i[1].tempo)
                )
                recommended_track.save()
                duration_playlist.append(recommended_track)
                playlist_ids.append(recommended_track.spotify_id)
                duration += datetime.timedelta(
                    milliseconds=recommendations[i[0]].duration_ms)
                print(duration)
            else:
                break
        playlist = Playlist(
            name='unnamed',
            duration=datetime.timedelta(milliseconds=np.sum(
                [t.duration_ms for t in duration_playlist]).item()),
            recommended_id_string=json.dumps({"uris": [
                f"spotify:track:{id}" for id in playlist_ids]}),
            based_on=track
        )
        playlist.save()
        for recommended_track in duration_playlist:
            playlist.tracks.add(recommended_track)
        playlist.save()
        return playlist

bpmsearchapp/forms.py
from django import forms


class SearchForm(forms.Form):
    song_title = forms.CharField(label='Song title', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'eg. American Idiot'}))
    target_tempo = forms.CharField(
        label='Target tempo', max_length=3, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'eg. 170 (optional)'}))
    target_pace = forms.CharField(label='Target pace', required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'eg. 5:45 (optional)'}))
    duration = forms.IntegerField(label='Duration in minutes', required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'eg. 30 (optional)'}))


class PlaylistForm(forms.Form):
    name = forms.CharField(label='Save Playlist to Spotify', max_length=50, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Playlist Name'}))

bpmsearchapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django.urls import reverse

import requests
import pprint
import base64
import json
import os
import datetime
from .forms import SearchForm, PlaylistForm
from .models import Track, Playlist

from .modules.spotify import SpotifyTrack


def index(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            track = Track.create_track(form.cleaned_data.get('song_title'))
            if form.data['target_pace']:
                pace = form.cleaned_data.get('target_pace').split(':')
                # 1177 is avg steps per km
                tempo = 1000/(
                    int(pace[0]) * 60 + int(pace[1])/60)
            elif form.data['target_tempo']:
                tempo = form.cleaned_data.get('target_tempo')
            else:
                tempo = 165
            if form.data['duration']:
                duration = form.cleaned_data.get('duration')
            else:
                duration = 60
            track.save()
            recommendations_playlist = Playlist.create_playlist(
                track, tempo, duration)
            return redirect('bpm:playlist', pk=recommendations_playlist.pk)
    else:
        form = SearchForm()
    return render(request, 'bpmsearchapp/index.html', {
        'form': form,
    })


def playlist(request, pk):
    if request.method == 'POST':
        form = PlaylistForm(request.POST)
        if form.is_valid():
            request.session['playlist_name'] = form.cleaned_data.get('name')
            return redirect(f'https://accounts.spotify.com/authorize?client_id={os.environ.get("SPOTIFY_CLIENT_ID")}&response_type=code&redirect_uri={os.environ.get("REDIRECT_URI")}&scope=playlist-modify-private')
    else:
        form = PlaylistForm()
        request.session['playlist_pk'] = pk
        playlist = Playlist.objects.get(pk=pk)
        total_seconds = playlist.duration.total_seconds()
        hours, remainder = divmod(total_seconds, 60*60)
        minutes, seconds = divmod(remainder, 60)
        duration = str(int(hours))+':'+str(int(minutes))+':'+str(int(seconds))

    return render(request, 'bpmsearchapp/playlist.html', {
        'form': form,
        'playlist': playlist,
        'duration': duration,
        'playlist_tracks': playlist.tracks.all(),
        'track': playlist.based_on})


def spotify_auth(request):
    request.session['auth_code'] = request.GET.get('code', '')
    playlist = get_object_or_404(
        Playlist, pk=request.session.get('playlist_pk'))
    playlist.name = request.session.get('playlist_name')
    playlist.save(update_fields=['name'])

    auth_response = requests.post(
        'https://accounts.spotify.com/api/token', data={
            'code': request.session['auth_code'],
            'client_id': os.environ.get('SPOTIFY_CLIENT_ID'),
            'client_secret': os.environ.get('SPOTIFY_CLIENT_SECRET'),
            'grant_type': 'authorization_code',
            'redirect_uri': os.environ.get("REDIRECT_URI")
        })

    user_id = requests.get('https://api.spotify.com/v1/me', headers={
        "Authorization": f"Bearer {auth_response.json()['access_token']}"}).json()['id']

    playlist_id = requests.post(f'https://api.spotify.com/v1/users/{user_id}/playlists',
                                headers={
                                    "Authorization": f"Bearer {auth_response.json()['access_token']}",
                                    "Content-Type": "application/json"
                                },
                                data=str(json.dumps(
                                    {"name": playlist.name, "public": "false"}))).json()['id']

    add_items_to_playlist_response = requests.post(f'https://api.spotify.com/v1/playlists/{playlist_id}/tracks',
                                                   headers={
                                                       "Authorization": f"Bearer {auth_response.json()['access_token']}",
                                                       "Content-Type": "application/json"
                                                   },
                                                   data=playlist.recommended_id_string)

    return redirect('bpm:playlist',
                    pk=request.session['playlist_pk'])

bpmsearchapp/templates/bpmsearchapp/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row justify-content-center p-3 h-100 pt-3" id="search-form-row">
    <div class="col-10 col-lg-7 pt-3" id="search-form">
        <form action="/" method="post">
            {% csrf_token %}
            {% for field in form  %}
            <div class="form-group">
                {{ field.label_tag }}{{field}}
            </div>

            {% endfor %}
            <div class="col m-0 pt-4">
                <button type="submit" class="btn btn-primary btn-lg btn-block ">
                    Generate Playlist
                </button>
            </div>
        </form>
    </div>

</div>
</div>
{% endblock %}

bpmsearchapp/templates/bpmsearchapp/playlist.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-3 mb-5" id="playlist">
    <div class="row pt-3">
        <div class="col-12 col-lg-6 pt-3" id="track-detail">
            <p>You searched for {{track.title}} by {{ track.artist }}</p>
            <p>It's BPM is {{track.tempo}}, and it is {{ track.duration }} long.</p>
            <p>The total duration of this playlist is {{ duration }}</p>
        </div>
        <div class="col-12 col-lg-6 pt-3" id="save-form">
            <form action="/playlist/{{playlist.pk}}" method="post">
                {% csrf_token %}
                {% for field in form  %}
                <div class="form-group">
                    {{ field }}
                </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary btn-lg btn-block ">Save Playlist to Spotify</button>
            </form>
        </div>
    </div>
    <div class="row" style="text-align: center;">
        <div class="col">
            <a href="{% url 'bpm:index'%}">Go back to search</a>
        </div>
    </div>
    <div class="row pt-3">
        <div class="col-12">
            <table class="table table-striped" id="playlist-table">
                <tr>
                    <th>Track Name</th>
                    <th>Artist</th>
                    <th>Tempo</th>
                    <th>Duration</th>
                </tr>
                {%for i in playlist_tracks%}
                <tr>
                    <td>{{i.title}}</td>
                    <td>{{i.artist}}</td>
                    <td>{{i.tempo}}</td>
                    <td>{{i.duration}}</td>
                </tr>
                {%endfor%}
            </table>
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}